{% set name = "pyflwdir" %}
{% set version = "0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyflwdir-{{ version }}.tar.gz
  sha256: 82d6b1c3898ac3d30167ec20c01f2184f02ca877607eaf2fee553b91cca16f5d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - affine
    - numba >=0.48
    - numpy
    - python >=3.6
    - scipy

test:
  imports:
    - pyflwdir
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/deltares/wflow/pyflwdir/
  summary: Fast methods to work with hydro- and topography data in pure Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DirkEilander
