{% set name = "pyflwdir" %}
{% set version = "0.5.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyflwdir-{{ version }}.tar.gz
  sha256: 03488c2a99fa0783cdbe233ea777361c20f2e5a8fd84cfebba6358409ffb3902

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python >=3.8
  run:
    - affine
    - numba >=0.54
    - numpy
    - python >=3.8
    - scipy

test:
  imports:
    - pyflwdir
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deltares/pyflwdir/
  summary: Fast methods to work with hydro- and topography data in pure Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DirkEilander
