{% set name = "pyflwdir" %}
{% set version = "0.5.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyflwdir-{{ version }}.tar.gz
  sha256: 3f25cf7a1f373332a2acb8addd98aa492bedb7e6695735ae0fd8fa55be9c6966

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - affine
    - numba >=0.54
    - numpy
    - python >=3.7
    - scipy

test:
  imports:
    - pyflwdir
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deltares/pyflwdir/
  summary: Fast methods to work with hydro- and topography data in pure Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DirkEilander
